// try-catch-finally 예시
try {
  console.log("try 블록")
} catch (err) {
  console.log("catch 블록")
} finally {
  console.log("finally 블록")
}

// try-finally 예시
try {
  console.log("try 블록")
} finally {
  console.log("finally 블록")
}
